version: '3.7'

services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: /bin/ash -c 'rm -rf tmp/pids/server.pid; bundle exec rails s -b 0.0.0.0'
    depends_on:
      - delayed_job
      - postgresql
      - webpack
    environment:
      LANG: C.UTF-8
    ports:
      - 3000:3000
    stdin_open: true # for Pry
    tty: true # for Pry
    volumes:
      - .:/workspace
      - gems_vol:/usr/local/bundle
      - node_modules_vol:/annict/node_modules
  delayed_job:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: /bin/ash -c 'bundle exec rails jobs:work'
    depends_on:
      - postgresql
    volumes:
      - .:/workspace
      - gems_vol:/usr/local/bundle
  webpack:
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile.local
    command: /bin/ash -c 'yarn webpack:start'
    volumes:
      - .:/workspace
      - node_modules_vol:/annict/node_modules
    ports:
      - 8080:8080
  postgresql:
    image: postgres:12.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379

volumes:
  # Exclude the gems/node_modules directory
  # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
  gems_vol:
  node_modules_vol:
