version: '3.7'

services:
  postgresql:
    image: postgres:14.2
    ports:
      - 35432:5432
    volumes:
      - postgresql14_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:5.0.5-alpine
    ports:
      - 36379:6379

volumes:
  postgresql14_data:
