version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: /bin/bash -c 'rm -rf tmp/pids/server.pid; bundle exec rails s -b 0.0.0.0'
    depends_on:
      - frontend
      - worker
      - postgresql
    environment:
      LANG: C.UTF-8
    ports:
      - 3000:3000
    stdin_open: true # for Pry
    tty: true # for Pry
    volumes:
      - .:/workspace:cached
      - gems_vol:/usr/local/bundle
      - node_modules_vol:/workspace/node_modules
  frontend:
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile.local
    command: /bin/bash -c 'npm run webpack:start'
    ports:
      - 3001:8080
    volumes:
      - .:/workspace:cached
      - node_modules_vol:/workspace/node_modules
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: /bin/bash -c 'bundle exec rails jobs:work'
    depends_on:
      - postgresql
    volumes:
      - .:/workspace:cached
      - gems_vol:/usr/local/bundle
  postgresql:
    image: postgres:12.4-alpine
    ports:
      - 35432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:5.0.5-alpine
    ports:
      - 36379:6379

volumes:
  # Exclude the gems/node_modules directory
  # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
  gems_vol:
  node_modules_vol:
